import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

Future<Uint8List> buildBillingPdf({
  required String billNumber,
  required String generatedBy,
  required String companyName,
  required String supportPhone,
  required String customerName,
  required String phone,
  required String city,
  required String address,
  required String invoiceType,
  required String paymentMethod,
  required List<Map<String, dynamic>> items,
  required double subtotal,
  required double gstRate,
  required double gstAmount,
  required double total,
}) {
  final pw.Document doc = pw.Document();

  pw.Widget cell(String text, {pw.TextStyle? style}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.symmetric(vertical: 4),
      child: pw.Text(text, style: style),
    );
  }

  doc.addPage(
    pw.MultiPage(
      pageFormat: PdfPageFormat.a4,
      margin: const pw.EdgeInsets.all(28),
      build: (pw.Context context) {
        return <pw.Widget>[
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: <pw.Widget>[
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: <pw.Widget>[
                  pw.Text(
                    companyName,
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 4),
                  pw.Text('Billing Invoice'),
                  if (supportPhone.trim().isNotEmpty) ...<pw.Widget>[
                    pw.SizedBox(height: 2),
                    pw.Text('Support: $supportPhone'),
                  ],
                ],
              ),
              pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.end,
                children: <pw.Widget>[
                  pw.Text(
                    billNumber,
                    style: pw.TextStyle(
                      fontSize: 14,
                      fontWeight: pw.FontWeight.bold,
                    ),
                  ),
                  pw.SizedBox(height: 2),
                  pw.Text('Generated by: $generatedBy'),
                ],
              ),
            ],
          ),
          pw.SizedBox(height: 16),
          pw.Divider(),
          pw.SizedBox(height: 10),

          pw.Text(
            'Customer',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 6),
          pw.Table(
            columnWidths: <int, pw.TableColumnWidth>{
              0: const pw.FixedColumnWidth(110),
              1: const pw.FlexColumnWidth(),
            },
            children: <pw.TableRow>[
              pw.TableRow(children: <pw.Widget>[
                cell('Name'),
                cell(customerName),
              ]),
              pw.TableRow(children: <pw.Widget>[
                cell('Phone'),
                cell(phone),
              ]),
              pw.TableRow(children: <pw.Widget>[
                cell('City'),
                cell(city),
              ]),
              pw.TableRow(children: <pw.Widget>[
                cell('Address'),
                cell(address),
              ]),
              pw.TableRow(children: <pw.Widget>[
                cell('Invoice Type'),
                cell(invoiceType),
              ]),
              pw.TableRow(children: <pw.Widget>[
                cell('Payment'),
                cell(paymentMethod),
              ]),
            ],
          ),

          pw.SizedBox(height: 16),
          pw.Text(
            'Items',
            style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 6),
          pw.Table(
            border: pw.TableBorder.all(color: PdfColors.grey600, width: 0.6),
            columnWidths: <int, pw.TableColumnWidth>{
              0: const pw.FlexColumnWidth(),
              1: const pw.FixedColumnWidth(40),
              2: const pw.FixedColumnWidth(70),
              3: const pw.FixedColumnWidth(80),
            },
            children: <pw.TableRow>[
              pw.TableRow(
                decoration: const pw.BoxDecoration(color: PdfColors.grey200),
                children: <pw.Widget>[
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text(
                      'Item',
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text(
                      'Qty',
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text(
                      'Price',
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                  pw.Padding(
                    padding: const pw.EdgeInsets.all(6),
                    child: pw.Text(
                      'Total',
                      style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                    ),
                  ),
                ],
              ),
              ...items.map((Map<String, dynamic> raw) {
                final String name = (raw['name'] ?? '').toString();
                final int qty = int.tryParse((raw['qty'] ?? 0).toString()) ?? 0;
                final double price =
                    double.tryParse((raw['price'] ?? 0).toString()) ?? 0;
                final double lineTotal = qty * price;
                return pw.TableRow(
                  children: <pw.Widget>[
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(name),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text(qty.toString()),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text('Rs ${price.toStringAsFixed(2)}'),
                    ),
                    pw.Padding(
                      padding: const pw.EdgeInsets.all(6),
                      child: pw.Text('Rs ${lineTotal.toStringAsFixed(2)}'),
                    ),
                  ],
                );
              }),
            ],
          ),

          pw.SizedBox(height: 14),
          pw.Align(
            alignment: pw.Alignment.centerRight,
            child: pw.Container(
              width: 220,
              child: pw.Column(
                children: <pw.Widget>[
                  pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: <pw.Widget>[
                      pw.Text('Subtotal'),
                      pw.Text('Rs ${subtotal.toStringAsFixed(2)}'),
                    ],
                  ),
                  pw.SizedBox(height: 4),
                  pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: <pw.Widget>[
                      pw.Text(
                        gstRate > 0
                            ? 'GST (${(gstRate * 100).toStringAsFixed(2)}%)'
                            : 'GST',
                      ),
                      pw.Text('Rs ${gstAmount.toStringAsFixed(2)}'),
                    ],
                  ),
                  pw.Divider(),
                  pw.Row(
                    mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                    children: <pw.Widget>[
                      pw.Text(
                        'Total',
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      ),
                      pw.Text(
                        'Rs ${total.toStringAsFixed(2)}',
                        style: pw.TextStyle(fontWeight: pw.FontWeight.bold),
                      ),
                    ],
                  ),
                ],
              ),
            ),
          ),

          pw.SizedBox(height: 18),
          pw.Divider(),
          pw.Text(
            'Thank you for choosing $companyName.',
            style: const pw.TextStyle(fontSize: 10),
          ),
        ];
      },
    ),
  );

  return doc.save();
}
