apiVersion: v1
kind: Service
metadata:
  name: a1-backend-service
  labels:
    app: a1-backend
spec:
  type: ClusterIP
  selector:
    app: a1-backend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
